symbols_meta:
  QQQ:
    group: Index
    can_trade: false
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    price_step_per_mark: 0.5
    retest_tolerance_multiplier: 1
    exchange: CBOE
    expiry_offset: 1
  TSLA:
    group: G1
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    price_step_per_mark: 1
    retest_tolerance_multiplier: 1
  AAPL:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    price_step_per_mark: 0.5
    retest_tolerance_multiplier: 1
  NVDA:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    price_step_per_mark: 0.5
    retest_tolerance_multiplier: 1
  AMD:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    price_step_per_mark: 0.5
    retest_tolerance_multiplier: 1
  PLTR:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    price_step_per_mark: 0.5
    retest_tolerance_multiplier: 1
  MU:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    price_step_per_mark: 0.5
    retest_tolerance_multiplier: 1
  TSLL:
    group: G1
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.04
    breakout_confirmation_distance: 0.07
    price_step_per_mark: 0.5
    retest_tolerance_multiplier: 1.8
  SPY:
    group: Index
    can_trade: false
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    price_step_per_mark: 0.5
    retest_tolerance_multiplier: 2
    exchange: CBOE
    expiry_offset: 1
  MNQ:
    can_trade: false
    contract_type: Future
    min_required_move_from_level: 5
    breakout_confirmation_distance: 2
    price_step_per_mark: 20
    retest_tolerance_multiplier: 3
    contract_month: 202606
    long:
      stop_loss: level_used - ( dynamic_tolerance.get('tolerance', 0) * app_config['symbols_meta'][symbol].get('retest_tolerance_multiplier', 1))
      take_profit: df['close'].iloc[-1] + (df['atr_14'].iloc[-2] * 2 )
    short:
      stop_loss: level_used + ( dynamic_tolerance.get('tolerance', 0) * app_config['symbols_meta'][symbol].get('retest_tolerance_multiplier', 1))
      take_profit: df['close'].iloc[-1] - (df['atr_14'].iloc[-2] * 2 )
  AMZN:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    price_step_per_mark: 0.5
    retest_tolerance_multiplier: 1


symbols:
  - QQQ
  - AAPL
  - AMD
  - AMZN
  - NVDA
  - PLTR
  - TSLA
  - SPY
  - INTC
  - HOOD
  - SPCX
  - MSFT
#  - MRVL
#  - WDC
#  - META
#  - SNDK
#  - GOOG
#  - MU


strike_increments:  # default is 2.5., don't put it here if it i 2.5
  QQQ: 1
  SPY: 1
  MU: 5
  INTC: 1
  SNDK: 5
  GOOG: 5
  HOOD: 1


options:
  use_manual_strikes: True
  max_otm_strikes_for_quotes: 3
  max_option_contracts_to_prepare: 5
